version: '3.1'
services:
  db_prod_encore:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: prodencoredb
      MYSQL_USER: prod_encore
      MYSQL_PASSWORD: prod_encore_password
    ports:
      - 3306:3306

  db_test_encore:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: testencoredb
      MYSQL_USER: test_encore
      MYSQL_PASSWORD: test_encore_password
    ports:
      - 3307:3306
